name: Unity build

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: CommonEnv
    
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64
          buildsPath: "build/"
          versioning: Semantic
      - name: Zip build
        run: zip -r WaterSurfaceBuild.zip build
      - name: Expose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: WaterSurfaceBuild.zip
        
    
    