name: Unity build

on:
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    environment: CommonEnv
    
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows
          buildsPath: "build/"
          versioning: Semantic
        
    
    